### ISSUE TITLE
Create APIs responsible for modifying existing bands

### ISSUE THREAD

**Issue by RanjeetNSuthar** [RanjeetNSuthar/Bands#4]
## Create 2 APIs
- Create an API that will update the details of an existing band in the database
- Create an API that will delete a specific band

**Comment by CodeAbsolute** [comment]
I want to work on this issue

**Comment by Codemaster3112** [comment]
I want to work on this issue

**Comment by RanjeetNSuthar** [comment]
@Codemaster3112 you have been assigned

**Comment by charleeBlaqTech** [comment]
has it been solved?

**Comment by RanjeetNSuthar** [comment]
yes
